### ISSUE TITLE
Configuration for Attacks instead of Hard Coding

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#1]
It would be nice to specify new attacks as JSON files that can be interpreted by the scanner. E.g. something like:

```
{
	"name":"Apache mod_status is Accessible",
	"location":"/server-status",
	"requirements": [
		{"equals": ["http-status-code", 200]},
		{"contains":["contents","Server Version: (.*)</dt>"]}
	]
}
```

With extra reporting options and such, this would clean the reporting code up.

**Comment by JosephGregg** [comment]
Have you considered using the databases provided by the [nikto](https://raw.githubusercontent.com/sullo/nikto/master/program/databases/db_tests) project for this purpose? I might be able to help if you want the attacks to be formatted as JSON.

**Comment by JosephGregg** [comment]
It looks like we would have to get written permission from nikto to use their database. Boo.

**Comment by s-rah** [comment]
Closing this in favour of another direction.
