### ISSUE TITLE
Grab additional header information for reporting

### ISSUE THREAD

**Issue by JosephGregg** [s-rah/onionscan#10]
Things such as X-Powered-By will reveal the PHP version.

**Comment by JosephGregg** [comment]
Tested this out and it seems to work. You can look [here](https://github.com/JosephGregg/onionscan/tree/grabheaders)

- Modified onionscan.go
- Modified report/onionscanreport.go

```
2016/04/11 16:16:55 Starting Scan of snip.onion
2016/04/11 16:16:55 This might take a few minutes..

2016/04/11 16:16:59 Attempting to Derive Server Type from Headers..
2016/04/11 16:16:59 	Server Version: Apache/2.2.15 (CentOS)
2016/04/11 16:16:59 Attempting to grab additional header information..
2016/04/11 16:16:59 	X-Powered-By: PHP/5.3.3
```

**Comment by s-rah** [comment]
Nice. Submit a PR and I'll pull this in. Might need to generalise this more later. But we should definitely do this.
