### ISSUE TITLE
Correlation Lab stopped working

### ISSUE THREAD

**Issue by yourzeppelin** [s-rah/onionscan#107]
Hello, all,

First let me thank you for the good work you've done! I've been waiting for software like this :) I tried yesterday and left it running on a laptop. After I came back, I tried to access the Correlation Lab , but it stopped working. I got this error:

`http: panic serving 127.0.0.1:59224: runtime error: makeslice: len out of range
goroutine 2770`

I can post full traceback if needed. Is there maximum correlations I can have? I've been running it with a pretty big list from Harry71's site.

**Comment by s-rah** [comment]
Huh...well that shouldn't happen!

I've have it running with 500,000+ correlations from scanning a large number of sites (15000+) so I don't think it is to do with size - though I have seen slow downs if any 1 site has more than 20,000). Can you post the whole trace?

Does this happen when you try to search for something or just loading it? Do you have any custom scans defined?

**Comment by yourzeppelin** [comment]
It happends when I'm just loading http://127.0.0.1:8080... I don't have any custom scans (yet, can't find documentation).

**Comment by yourzeppelin** [comment]
I tried to start concurrent onionscan processess.. is this bad?

**Comment by s-rah** [comment]
The database is file locked - so if the two processes are attempting to read from the same database one of them will stall (You can configure the number of concurrent pipelines in OnionScan using the `batch` parameter) 

Do you have the /templates directory in the same directory you are running the binary from? That path is currently hardcoded and OnionScan will fail to start the correlation lab if it can't find the /templates path.

**Comment by yourzeppelin** [comment]
Yes, I noticed that it tries to find /templates directory and I "hacked" it by copying in current directory. 

I'll wipe the db and start all over. Thanks for the hint about batch parameter. Thanks a lot for your efforts, s-rah!
