### ISSUE TITLE
Onionscan fails to build on 32 bit systems

### ISSUE THREAD

**Issue by archey** [s-rah/onionscan#108]
I wanted to let you know that onionscan fails to build on 32bit systems such as i686,armv6h,armv7h and armv8. This is due to an integer overflow in the database pkg of github.com/HouzuoGuo/tiedot. There is an open issue on this for the developer 

https://github.com/HouzuoGuo/tiedot/issues/68

Hopefully they get it fixed soon, just opening this to make you aware of the situation.

Build output on i686:

golang.org/x/net/html/atom
golang.org/x/crypto/openpgp/errors
golang.org/x/crypto/cast5
github.com/HouzuoGuo/tiedot/dberr
golang.org/x/crypto/curve25519
github.com/HouzuoGuo/tiedot/gommap
github.com/HouzuoGuo/tiedot/tdlog
github.com/s-rah/onionscan/model
github.com/rwcarlsen/goexif/tiff
golang.org/x/net/html
golang.org/x/net/proxy
golang.org/x/crypto/openpgp/armor
github.com/HouzuoGuo/tiedot/data
golang.org/x/crypto/openpgp/elgamal
golang.org/x/crypto/openpgp/s2k
# github.com/HouzuoGuo/tiedot/data
../src/github.com/HouzuoGuo/tiedot/data/hashtable.go:48: constant 3735928559 overflows int
golang.org/x/crypto/ed25519/internal/edwards25519
golang.org/x/crypto/ssh/terminal
golang.org/x/crypto/openpgp/packet
github.com/rwcarlsen/goexif/exif
golang.org/x/crypto/ed25519
github.com/s-rah/onionscan/utils
golang.org/x/crypto/ssh
github.com/s-rah/onionscan/report
golang.org/x/crypto/openpgp
github.com/s-rah/onionscan/onionscan/steps

**Comment by s-rah** [comment]
Hi @archey thanks for reporting - we are aware of this issue and are currently tracking it in: #84 

Thanks, 
Sarah
