### ISSUE TITLE
Web UI starts by default, but there is no indication of this

### ISSUE THREAD

**Issue by laanwj** [s-rah/onionscan#112]
I noticed recently that OnionScan seemed to hang after scanning when invoked via the command line, e.g.:
```
$ ./osc -scans none -verbose 4hwyik7xxwb6pbvb.onion
2016/11/12 15:46:29 Starting Scan of 4hwyik7xxwb6pbvb.onion
2016/11/12 15:46:29 This might take a few minutes..

--------------- OnionScan Report ---------------
Generating Report for: 4hwyik7xxwb6pbvb.onion

No risks were found.
<Need to Ctrl-C out>
```
First thought there was a hanging thread, but it turns out that this is because the web UI is started. With `-webport 0` the old behavior returns. Should we be more verbose about this?

**Comment by s-rah** [comment]
Yeah, this was a really quick bug fix I made....basically....we need to keep track of each go routine that we run, so that if then webport isn't active then onionscan will wait for the scans to finish - there is currently no mechanism for doing that.
