### ISSUE TITLE
Cannot go get github.com/s-rah/onionscan

### ISSUE THREAD

**Issue by sransomau** [s-rah/onionscan#115]
Could someone please help out a Noobie?

Trying to install on  Ubuntu 16.04.1 x64 
 I keep getting the following error when I try to get onionscan

 gvm use go1.4
Now using version go1.4
machine:~# go get github.com/s-rah/onionscan
# golang.org/x/crypto/ssh
.gvm/pkgsets/go1.4/global/src/golang.org/x/crypto/ssh/keys.go:903: undefined: base64.RawStdEncoding

Really appreciate any help!

Regards
Scott

**Comment by sransomau** [comment]
Never mind updated to go 1.7 all fine

**Comment by s-rah** [comment]
Beat me to it! Glad you got it worked out!

We do need better dependency management though, and need to be be explicit about go versions. A note to myself to add that to the backlog.
