### ISSUE TITLE
how can I go get golang.org/x/net/crypto?

### ISSUE THREAD

**Issue by tomyxy** [s-rah/onionscan#123]
Why I print "go get golang.org/x/net/crypto" ,and it says
package golang.org/x/net/crypto
        imports golang.org/x/net/crypto
        imports golang.org/x/net/crypto: cannot find package "golang.org/x/net/crypto" in any of:
        /usr/local/go/src/golang.org/x/net/crypto (from $GOROOT)
        /home/gopath/src/golang.org/x/net/crypto (from $GOPATH)
and then I find it that golang.org/x/net/crypto is 404. So how can I go get crypto?

**Comment by quenbyako** [comment]
same thing. did you solve it?
