### ISSUE TITLE
Have anyone meet this error during installing the onionscan 

### ISSUE THREAD

**Issue by miaoxu9999** [s-rah/onionscan#134]
ERROR: Unknown hidden service type: notarealhiddenservice.onion

**Comment by 1ab1** [comment]
I don't think `notarealhiddenservice.onion` exists. Can you be more specific about the installation. 
For eg: OS/ version/ build no.. etc

**Comment by s-rah** [comment]
`notarealhiddenservice.onion` doesn't exist and does not conform to the format of standard hidden services, as such onionscan will error. You should try your installation with a known hidden service address like facebookcorewwwi.onion

**Comment by HubGrit** [comment]
If I do sudo $GOPATH/bin/onionscan facebookcorewwwi.onion the program runs ok, as it does with other existing onion sites.  But when I run my own onion site that i can view ok (from a different device and network) and I run onionscan on it I also get ERROR: Unknown hidden service type
