### ISSUE TITLE
getting socks connections errors after it was working previously

### ISSUE THREAD

**Issue by hotelzululima** [s-rah/onionscan#14]
bin/onionscan   -torProxyAddress 127.0.0.1:9050 -verbose -jsonReport http://legionhiden4dqh4.onion/
2016/04/11 20:48:30 Starting Scan of http://legionhiden4dqh4.onion/
2016/04/11 20:48:30 This might take a few minutes..

2016/04/11 20:48:30 Error running scanner: Get http://http://legionhiden4dqh4.onion/: Can't complete SOCKS5 connection.

tor message

20:48:30 [NOTICE] Application asked to connect to port 0. Refusing. [18
 x   duplicates hidden]

18 SocksPort 127.0.0.1:9050 # Default: Bind to localhost:9050 for local
 x     connections.

tor is being started by arm
tor is latest git pull on latest yosemite

**Comment by s-rah** [comment]
We currently don't support "http://" prefix  in URLs. Try running the application without the prefix i.e. `bin/onionscan -torProxyAddress 127.0.0.1:9050 -verbose -jsonReport legionhiden4dqh4.onion`

Thanks,

Sarah

**Comment by hotelzululima** [comment]
that was it Sarah.. closing issue.. thanx!!
