### ISSUE TITLE
Consider CARONTE's ideas for location leaks

### ISSUE THREAD

**Issue by NullHypothesis** [s-rah/onionscan#15]
There's a 2015 research paper that presented a tool, CARONTE, that attempts to find a number of configuration issues that can cause location leaks:
https://software.imdea.org/~juanca/papers/caronte_ccs15.pdf

In particular, they talk about:
- Finding "broken" links on onion pages (Section 3.3.1).
- Finding unique strings on onion pages, and then google for them (Section 3.3.2).
- Finding reused X.509 certificates (Section 3.3.3).

The techniques turned out to be mildly successful:

> We apply CARONTE to 1,974 hidden services, fully recovering the IP address of 100 (5%) of them.

Maybe some of it is helpful to onionscan!

**Comment by s-rah** [comment]
This looks very interesting. Thanks! Agreed these vectors should be captured.

**Comment by s-rah** [comment]
Breaking this down into a number of tasks:

#42
#43
#44
#45
