### ISSUE TITLE
Extract Page Title

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#19]
It would be nice to be able to have some grasp over what the page is about  - `<tiitle>` should be good enough, and is another possible fingerprinting mechanism.

**Comment by s-rah** [comment]
Merged in 2ff00f6a6d412e887d77ca6bd9b715892065b78e

**Comment by JburkeRSAC** [comment]
Newer versions do not seem to have the <title> parsing from https://github.com/s-rah/onionscan/commit/2ff00f6a6d412e887d77ca6bd9b715892065b78e

See https://github.com/s-rah/onionscan/blob/master/report/onionscanreport.go and search for the word "title" it is absent
