### ISSUE TITLE
Extract + Fingerprint Encryption Keys

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#20]
If we come across an armored key in any form we should process it, mostly to pull out email and version string if there is one.

**Comment by dballard** [comment]
taking a look at this

**Comment by s-rah** [comment]
I pushed an initial version of this a few days ago. Fingerprinting still needs to be done + redactor to scan more pages #32

**Comment by dballard** [comment]
https://github.com/s-rah/onionscan/pull/47
Extracts sha1 ffingerprint from x/crypto/openpgp

Future: 
- can we manually gen an md5 hash that matchs what other tools tell me my key is? because the x/crypto/openpgp fingerprint dfoesn't match

- call online services for matching?

**Comment by s-rah** [comment]
@dballard  I've updated the code - fea4c84b0b83db9a534d29cad4772c9a9ecbdbbe to use KeyIdShortString() instead of the fingerprint  which provides a key id like gpg --list-keys - https://godoc.org/golang.org/x/crypto/openpgp/packet#PublicKey.KeyIdString - not perfect perhaps, but more relatable and good enough for now.
