### ISSUE TITLE
Load domains to check from a file

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#21]
I've heard from more than a couple of people already who have wrapped OnionScan in python/perl/bash just to scan more than 1 domain.

Let's make this easy and provide a `-f` option. Each domain on a single line.

**Comment by ajvb** [comment]
Just to clarify, the `-f` option take a `.txt` file (`-f domains.txt`) and iterate over each?

**Comment by s-rah** [comment]
@ajvb is working on this.
