### ISSUE TITLE
Check http headers

### ISSUE THREAD

**Issue by antoniaklja** [s-rah/onionscan#25]
Hello, checking specific http header might be usefull. Maybe new scanner, like http_headers_scanner?
In the future it can be expanded by http injection flaws.

See OWASP recomendations: https://www.owasp.org/index.php/List_of_useful_HTTP_headers

What do you think about it?

**Comment by antoniaklja** [comment]
I can prepare initial version of this module if you wish.

**Comment by PeterTonoli** [comment]
I was going to put a new issue in for refactoring the header checks, as I've got a couple of checks to commit too - you've beaten me to the punch :-)

**Comment by antoniaklja** [comment]
I've added basic extraction of HTTP headers. I think that http_scanner.go is good place for analysing vulnerable and missing headers.

**Comment by s-rah** [comment]
Merged in d83d10bd93c9d8d74d438134af672b28cda630b3

**Comment by s-rah** [comment]
Next step in this is to add checks in the Reporting, although I'd like to do #18 first.

**Comment by antoniaklja** [comment]
I've added additional commit with checks http header during reporting.

**Comment by s-rah** [comment]
129ee4f8f4bdc34b826cf29cd9ae6a982921f5c4
