### ISSUE TITLE
SSH-key checking

### ISSUE THREAD

**Issue by 0x27** [s-rah/onionscan#3]
A lot of hidden services (close to 3% in my last big scan) are configured so that the .onion address serves all ports.

If SSH is being served, you can grab the key fingerprint and sometimes uncloak the HS by checking it against Shodan or your own database of scans.

Example code (in Python) to do this is here: https://github.com/0x27/ssh_keyscanner

**Comment by s-rah** [comment]
Looks like there are two new rulesets here:

1. Onion configured to serve more than 1 port - not a terrible idea, but certainly leaves open the possibility of a misconfiguration.
2. SSH Key checking

**Comment by s-rah** [comment]
Have a working prototype for this, will be up soon

**Comment by s-rah** [comment]
Fingerprinting added in 44e6d5c9557497754e12f0882d9f763e915de4a9  - still would be cool to lookup the fingerprint in a DB.

**Comment by 0x27** [comment]
@s-rah - Its possible to search ssh keys on Shodan, with the Shodan API. There is even a Go library: https://github.com/ns3777k/go-shodan

Still getting to grips with Go, slowly, coming up to exams here though so its slow going.

Hypothetically, an imaginary friend was able to deanonymize a good number of services by doing that (Shodanning the fingerprints)...

**Comment by PeterTonoli** [comment]
Might help to look at #26 too, when implementing..

**Comment by s-rah** [comment]
Closing this in favor of #73
