### ISSUE TITLE
Collect links to external sites by analysing html source code.

### ISSUE THREAD

**Issue by antoniaklja** [s-rah/onionscan#31]
We can collect all external links by adding checking of html source code (optionally javascript) and find links to clearnet sites (Hight Risk) and other onion sites (Low Risk).

- <imr src=?
- <a href=?
- <script src=?
- <iframe src=?
- <LINK href=?

and so on.

What do you think about it?

**Comment by s-rah** [comment]
I've been looking at this recently. There are a number of different threat models to consider for analyzing links, some thoughts:

* The mere presence of a link isn't necessarily high or low risk regardless of clearnet or onion.
* Both clearnet and onion links can be used to fingerprint a site (If site A only links to B and site B links to site A then there may be relationship between A and B)
* There is already some code in OnionScan to pull out links, although this could be greatly improved.

We could have this work in conjunction with #27 to give a Panopticlick like report analyzing who you link to, and seeing if they link back - that would help in detecting relationships between sites.

Then there are other links that may pose a threat: pulling in images/javascript/css from a third party site (relying on javascript entirely...). 

So I think we should:

* Modify the current code to pull out links to images, scripts, css resources (we should be scanning these if they are local, and making a note if they are 3rd party)
* Collect a list of external links - separated into clearnet and onion - including 3rd party resources.
* Report stats on these & a risk on 3rd party imports. 
* Think about how we build #27 to make this more useful.
