### ISSUE TITLE
Add Option to Output Simple Report in JSON Format

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#35]
We output the raw scan data, we should also optionally output SimpleReport as JSON (both as part of the normal JSON output and as an independent blob.

**Comment by antoniaklja** [comment]
Hi, what do you mean by that? Could you give me more info?

**Comment by s-rah** [comment]
Simple Report currently outputs something like:

`High Risk Issues: 5`
followed by:
`Apache mod_status is Exposed`
`Why is this bad: blah blah`
`How to Fix: blah blah`

It would be good to get this output into an (optional) JSON output so:

`{risks:[{"title":"Apache mod_status Exposed","description":".....","fix":"Disable mod_status or server on a different port than the onion service exposes"}]}`

**Comment by antoniaklja** [comment]
Ok, I will do that.

**Comment by s-rah** [comment]
Likely something for #73

**Comment by laanwj** [comment]
Had a try at this in #81.
