### ISSUE TITLE
Getting an error trying to run onionscan

### ISSUE THREAD

**Issue by cryptoishard** [s-rah/onionscan#4]
I'm running Ubuntu GNOME 15.04 with golang package installed.

~/onionscan$ ./onionscan.go 
./onionscan.go: line 1: package: command not found
./onionscan.go: line 3: syntax error near unexpected token `newline'
./onionscan.go: line 3: `import ('

**Comment by s-rah** [comment]
Hi,

You will need to either compile the package `go install github.com/s-rah/onionscan` and then run the program in `./bin/onionscan`.

Or, you can just do `go run github.com/s-rah/onionscan.go` to execute it without compiling.

**Comment by cryptoishard** [comment]
Just a semi unrelated question - have you thought about importing something like nikto's webscanner into os.ScanPage ? So it tests a lot more possible flaws with site?

Reference: https://github.com/sullo/nikto

Thanks only trying to be of use.

**Comment by hotelzululima** [comment]
Hi Sarah,
    you prolly want to put the above 
"You will need to either compile the package go install github.com/s-rah/onionscan and then run the program in ./bin/onionscan.

Or, you can just do go run github.com/s-rah/onionscan.go to execute it without compiling."

into the README.md
btw I am NOT a go dev/prog/user so was struggling for a few minutes till the google results came in :) 
ie how the fuck do I use this shite(go dev workflow in general)? :)

**Comment by s-rah** [comment]
Added some instructions on grabbing the code and installing with go into README. Thanks.
