### ISSUE TITLE
Extract HTTPS Certificates

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#43]
See #15 

This involves another web scanner on port 443. (Also detection on ports 80)

**Comment by s-rah** [comment]
Can be expanded by #46

**Comment by sainslie** [comment]
I just started to build this in conjunction to #48 and it'll affect #15 and #46 too. Go has built-in in support for just this sort of thing. Which data formats should I consider using for storing the data-set after extracting and parsing the X.509 data? It's best if it's a popular data representation format but I'm also considering after-the-fact usage.

I also thought about an additional potential concept of using public APIs to consult public databases to ascertain if additional X.509 credentials exist for similar or identical hostnames or other actionable details extracted from the data including #45 in the X.509 data.

**Comment by s-rah** [comment]
Added in 76ffa74b5dca59c4aba087710d46b1121d2065cc

**Comment by s-rah** [comment]
Closing this, we should probably expand this capability into the other protocols like X.509 - currently we output the entire certificate object which I think is likely the best
