### ISSUE TITLE
Attempt to grab /private_key

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#52]
This would be a critical server failure.

**Comment by s-rah** [comment]
Partially implemented in 872555c1df2d9988b356a9d64b420941c157983a

**Comment by laanwj** [comment]
Although the `/private_key` is still fetched, it looks like `AnonymityReport.PrivateKeyDetected` is no longer set since fbdf6f202c9956dc53caaeb8c7e7462f09e9acc4

**Comment by s-rah** [comment]
Ah yes, the older partial implementation was very basic and had many false positives, need to write a new one which looks for a private key block in the fetched page.
