### ISSUE TITLE
Service detection for non standard ports

### ISSUE THREAD

**Issue by 0x27** [s-rah/onionscan#55]
While running OnionScan today, I noted an unusual edge where a service is not on the expected port.

```
2016/08/11 09:57:12 ERROR: Get http://xxxxxxxxxxxxxxxx.onion/images: malformed HTTP response "SSH-2.0-OpenSSH_7.2"
```

Effectively, OnionScan tries to run HTTP fingerprinting on an SSH service due to the SSH daemon being bound to port 80.

The suggested enhancement that I can think of is to do some rudimentary banner parsing on connect and engage the correct fingerprinting engine based on the response.

**Comment by s-rah** [comment]
Yeah, I've seen this before too and agree with the approach. We've got #46 tracking it - closing this as a duplicate
