### ISSUE TITLE
Error getting Onionscan

### ISSUE THREAD

**Issue by bl4ckh0l3z** [s-rah/onionscan#58]
Getting Onionscan, I have the following error on Debian 8.5 x64 3.16.7, go 1.3.3:

![onionscan_error](https://cloud.githubusercontent.com/assets/8762278/18088402/b329efd6-6eba-11e6-9d99-e2cf790b0f51.png)

**Comment by s-rah** [comment]
Please see #56.

You will likely need to update you golang.org/x/crypto packages and/or upgrade go from 1.3 to a new version (the latest is currently 1.7)

Thanks, 

s-rah

**Comment by bl4ckh0l3z** [comment]
Ouch...thanks sister!  :)
Excellent work!
