### ISSUE TITLE
onionscan doesn't compile on 32-bit (dependency issue)

### ISSUE THREAD

**Issue by laanwj** [s-rah/onionscan#84]
One of the dependencies, `HouzuoGuo/tiedot` explicitly only [works on x86_64](https://github.com/HouzuoGuo/tiedot/blob/master/data/hashtable.go#L41) right now, and fails to build on ARM32:

> tiedot should be compiled/run on x86-64 systems.
> If you decide to compile tiedot on 32-bit systems, the following integer-smear algorithm will cau
> se compilation failure
> due to 32-bit interger overflow; therefore you must modify the algorithm.
> Do not remove the integer-smear process, and remember to run test cases to verify your mods.

Doesn't seem that difficult to solve (possibly just replacing int by uint64), however this needs to be resolved before onionscan can run on most Android devices and such.

Edit: There's an upstream issue for this https://github.com/HouzuoGuo/tiedot/issues/68 and it's being worked on, there is even a 32-bit branch but it isn't integrated into mainline yet.

**Comment by archey** [comment]
You guys think he's ever gonna fix it, its been busted for along time now

**Comment by laanwj** [comment]
The issue is clearly not high on the author's priority list. Someone that cares about this should probably pick it up and try to push a solution forward; waiting for other people to fix things works very badly in open source.

I only noticed this because I was trying to compile this on my travel laptop, which is a 32-bit "toy". Even modern phones tend to have 64-bit CPUs so I'm not sure how important this is in practice.

For me the workaround to change the int to an explicit int64 seemed to work.

**Comment by archey** [comment]
@s-rah @laanwj I worked with the upstream dev of tiedot and this issue has been resolved. I am not sure when they will release a new version with the patches, but it has been fixed and tested on 32 bit systems

**Comment by archey** [comment]
@s-rah I believe this can be closed as we just built onionscan on i686, armv6, armv7 and armv8 without any issues from this tiedot/db dep. Just wanted to give you a heads up, I have closed our issue for it.
