### ISSUE TITLE
Better onion validation.

### ISSUE THREAD

**Issue by s-rah** [s-rah/onionscan#95]
I just had a run attempt to scan "blablahbal.com/onion" because of a bad source regex - however instead of returning an error, OnionScan went through the motions and only failed because it couldn't create the file needed for the report (because of the forward slash) - we should add extra validation on incoming onions.

**Comment by laanwj** [comment]
What do we want to allow here?

The strictest possible check would be:
```
^[a-z2-7]{16}\.onion$
```
However I remember seeing some subdomains of onions used as well, e.g. `antiscambrasil.torpress2sarn7xw.onion` in [the master list](https://github.com/automatingosint/osint_public/blob/master/onionrunner/onion_master_list.txt) here. I guess any valid (combination of) subdomains should be accepted as well?

**Comment by s-rah** [comment]
> I guess any valid (combination of) subdomains should be accepted as well?

Yes. It should validate that it is a correct URL and (for now) that the tld is `.onion`.
